databases:
  - name: agrosys-db
    databaseName: agrosys
    user: agrosys_user
    plan: free

services:
  - type: web
    name: agrosys
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: agrosys-db
          property: connectionString
      - key: JWT_SECRET
        value: agrosys_super_secure_production_jwt_key_2026_demo!
      - key: WHATSAPP_VERIFY_TOKEN
        value: token_seguro_agrosys_wa_2026
      - key: GEMINI_API_KEY
        sync: false
